# Generated by Django 5.1.6 on 2025-11-02 20:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('frete_uuid', models.UUIDField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('AGUARDANDO_PAGAMENTO', 'Aguardando Pagamento'), ('EXPIRADO', 'Expirado'), ('PAGO', 'Pago')], default='AGUARDANDO_PAGAMENTO', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
