# Generated by Django 5.1.6 on 2025-11-03 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='codigo_entrega',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
