PAGAMENTO_STATUS_AGUARDANDO_PAGAMENTO = "AGUARDANDO_PAGAMENTO"
PAGAMENTO_STATUS_EXPIRADO = "EXPIRADO"
PAGAMENTO_STATUS_PAGO = "PAGO"

PAGAMENTOS_STATUS = (
    (PAGAMENTO_STATUS_AGUARDANDO_PAGAMENTO, "Aguardando Pagamento"),
    (PAGAMENTO_STATUS_EXPIRADO, "Expirado"),
    (PAGAMENTO_STATUS_PAGO, "Pago")
)