# Generated by Django 5.1.6 on 2025-11-01 16:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.CharField(max_length=100)),
                ('cnpj', models.CharField(max_length=18)),
                ('nome_empresa', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Localizacao',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cep', models.CharField(max_length=9)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
                ('rua', models.CharField(max_length=100)),
                ('numero', models.IntegerField()),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=18)),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=20)),
                ('cnh', models.CharField(blank=True, max_length=15)),
                ('data_ultima_viagem', models.DateTimeField(null=True)),
                ('estado', models.CharField(choices=[('DISPONIVEL', 'Disponível'), ('RESERVADO', 'Reservado'), ('EM_TRANSPORTE', 'Em transporte'), ('INDISPONIVEL', 'Indisponível')], default='DISPONIVEL', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Caminhao',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('placa', models.CharField(max_length=10)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('ano_fabricacao', models.DateField()),
                ('peso', models.IntegerField()),
                ('altura', models.FloatField()),
                ('capacidade', models.FloatField()),
                ('material_reservatorio', models.CharField(choices=[('ACO', 'Aço'), ('ALUMINIO', 'Alumínio')], max_length=100)),
                ('data_ultima_viagem', models.DateTimeField(null=True)),
                ('estado', models.CharField(choices=[('DISPONIVEL', 'Disponível'), ('RESERVADO', 'Reservado'), ('EM_TRANSPORTE', 'Em transporte'), ('INDISPONIVEL', 'Indisponível')], default='DISPONIVEL', max_length=50)),
                ('localizacao_atual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localizao_atual', to='api.localizacao')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Frete',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo_produto', models.CharField(choices=[('CHILENO', 'Chileno'), ('TOLUENO', 'Tolueno'), ('HEXANO', 'Hexano'), ('BENZENO', 'Benzeno'), ('SOLVENTE_C6', 'Solvente C6'), ('AGUARRAS', 'Aguarrás'), ('GASOLINA', 'Gasolina'), ('METANOL', 'Metanol'), ('ETANOL', 'Etanol'), ('GLICERINA', 'Glicerina'), ('BIODIESEL', 'Biodiesel'), ('ESTIRENO', 'Estireno'), ('OLEO_DIESEL', 'Óleo Diesel'), ('OLEO_MINERAL', 'Óleo Mineral')], max_length=50, null=True)),
                ('quantidade', models.IntegerField(null=True)),
                ('data_coleta', models.DateTimeField(null=True)),
                ('data_entrega', models.DateTimeField(null=True)),
                ('preco', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('caminhao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='caminhao', to='api.caminhao')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to='api.cliente')),
                ('localizacao_coleta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='localizacao_coleta', to='api.localizacao')),
                ('localizacao_entrega', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='localizacao_entrega', to='api.localizacao')),
                ('motorista', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='motorista', to='api.motorista')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
