# Generated by Django 5.1.6 on 2025-11-01 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_frete_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caminhao',
            name='localizacao_atual',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='localizao_atual', to='api.localizacao'),
        ),
    ]
