# Generated by Django 5.1.6 on 2025-11-01 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_caminhao_localizacao_atual'),
    ]

    operations = [
        migrations.AddField(
            model_name='frete',
            name='status',
            field=models.CharField(choices=[('EM_ANALISE', 'Em análise'), ('RECUSADO', 'Recusado'), ('AGUARDANDO_COLETA', 'Aguardando coleta'), ('EM_ANDAMENTO', 'Em andamento'), ('FINALIZADO', 'Finalizado')], default='EM_ANALISE', max_length=50),
        ),
    ]
