# Generated by Django 5.1.6 on 2025-11-02 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_frete_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caminhao',
            old_name='estado',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='motorista',
            old_name='estado',
            new_name='status',
        ),
    ]
