# Generated by Django 5.1.6 on 2025-11-03 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_estado_caminhao_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='frete',
            name='codigo_entrega',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
